#@ load("@ytt:data", "data")
jobs:
- name: #@ data.values.job_name + "-job"
  plan:
  - task: #@ data.values.task_name
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
      run:
        path: echo
        args: #@ data.values.args
