resources:
- name: repo
  type: git
  check_every: 30m
  source:
    uri: https://github.com/concourse/examples
    branch: ((branch))

- name: golang
  type: registry-image
  source:
    repository: golang
    tag: latest

jobs:
- name: test
  public: true
  plan:
  - in_parallel:
    - get: repo
      trigger: true
    - get: golang
  - task: tests
    image: golang
    file: repo/tasks/go-test.yml
    params: {MODULE: apps/golang}

- name: build
  public: true
  plan:
  - in_parallel:
    - get: repo
      passed: [test]
      trigger: true
    - get: golang
  - task: build
    image: golang
    file: repo/tasks/go-build.yml
    params:
      MODULE: apps/golang
      BINARY_NAME: ascii-banner
  - task: run-binary
    image: golang
    file: repo/apps/golang/binary-test.yml
  # Could then upload the tgz file somewhere like S3
