resources:
- name: branch
  type: git
  source:
    uri: https://github.com/jutkko/examples
    branch: ((branch))

- name: examples
  type: git
  source:
    uri: https://github.com/jutkko/examples

- name: build-artifact
  type: gcs
  source:
    bucket: concourse-examples
    json_key: ((gcp_service_account_key))
    regexp: multi-branch/features/((feature))/my-app-(.+)\.tgz

jobs:
- name: test
  plan:
  - in_parallel:
    - get: branch
      trigger: true
    - get: examples
  - task: unit
    file: examples/tasks/go-test.yml
    input_mapping: {repo: branch}
    params: {MODULE: apps/golang}

- name: build
  plan:
  - in_parallel:
    - get: branch
      passed: [test]
      trigger: true
    - get: examples
  - task: build
    file: examples/tasks/go-build.yml
    params:
      MODULE: apps/golang
      BINARY_NAME: my-app
    input_mapping: {repo: branch}
