resources:
- name: branch
  type: git
  source:
    uri: https://github.com/jutkko/examples
    branch: ((branch))

- name: examples
  type: git
  source:
    uri: https://github.com/jutkko/examples

jobs:
- name: test
  plan:
  - in_parallel:
    - get: branch
      trigger: true
    - get: examples
  - task: unit
    vars: ((golang))
    file: examples/tasks/go-test.yml
    input_mapping: {repo: branch}
    params: {MODULE: apps/golang}

- name: build
  plan:
  - in_parallel:
    - get: branch
      passed: [test]
      trigger: true
    - get: examples
  - task: build
    file: examples/tasks/go-build.yml
    params:
      MODULE: apps/golang
      BINARY_NAME: my-app
    input_mapping: {repo: branch}
