name: "check my bundlephobia"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bundlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: web3@1.6.1
      - uses: carlesnunez/check-my-bundlephobia@v1
        with:
          repo-token: ${{ secrets.BUNDEL_TOKEN }}
          strict: true
          threshold: 500
          ignore-dev-dependencies: true
